# name: unigenex_env
# channels:
#   - conda-forge
#   - defaults
# dependencies:
#   - python=3.10
#   - pandas
#   - numpy
#   - matplotlib
#   - pip
#   - pip:
#     - survminer  # Packages not in conda can go here


conda create --name unigenex_env python=3.10 -y
conda activate unigenex_env

pip install flash-attn==2.5.5 --no-build-isolation

pip install ipykernel
python -m ipykernel install --user --name unigenex_env --display-name unigenex_env

cp Arial* /home/xwanaf/.conda/envs/unigenex_env/lib/python3.10/site-packages/matplotlib/mpl-data/fonts/ttf/
rm ~/.cache/matplotlib -rf  

./Gen_UGEatlas.sh 2>&1 | tee debug.log

scanpy==1.9.6
scib==1.1.5
setuptools<82

# torch==2.10.0
# torchvision==0.25.0
# torchaudio==2.10.0